
<h2>Notes</h2>
<div data-component="Callout" data-prop="W3sidHlwZSI6Im1keEF0dHJpYnV0ZSIsIm5hbWUiOiJ2YXJpYW50IiwidmFsdWUiOiJpbXBvcnRhbnQifV0=">
  <p>This release has been superseded. Please use version <a href="/docs/release-notes/agent-release-notes/python-release-notes/python-agent-286268">2.86.2.68</a> or higher.</p>
</div>
<p>This release of the Python agent includes various bug fixes as described below.</p>
<p>The agent can be installed using easy_install/pip/distribute via the <a href="https://pypi.python.org/pypi/newrelic">Python Package Index</a> or can be downloaded directly from the New Relic <a href="http://download.newrelic.com/python_agent/release/">download site</a>.</p>
<h2>Bug Fixes</h2>
<ul>
  <li>
    <p><strong>Handle exceptions generated by Tornado 4 AsyncHTTPClient during fetch</strong></p>
    <p>Exceptions generated by a call to the Tornado 4 AsyncHTTPClient resulted in an agent instrumentation error. Exceptions generated by AsyncHTTPClient are now recorded and properly handled.</p>
  </li>
  <li>
    <p><strong>Using gevent/eventlet on Python 3.6 resulted in a RecursionError</strong></p>
    <p>Python 3.6 introduced a <a href="https://github.com/python/cpython/commit/328067c468f82e4ec1b5c510a4e84509e010f296">change</a> to the ssl library. This change can result in a <a href="https://bugs.python.org/issue29149">recursion error</a> when the New Relic agent imports ssl prior to eventlet/gevent patching the ssl library (as is the case with use of the newrelic-admin script). This recursion error has been mitigated when using newrelic-admin to start applications.</p>
  </li>
</ul>
