
<h2>Notes</h2>
<p>This release of the Python agent adds support for Python 3.7 and contains various bug fixes.</p>
<p>The agent can be installed using easy_install/pip/distribute via the <a href="https://pypi.python.org/pypi/newrelic">Python Package Index</a> or can be downloaded directly from the New Relic <a href="http://download.newrelic.com/python_agent/release">download site</a>.</p>
<h2>New Features</h2>
<ul>
  <li>
    <p><strong>Support Python 3.7</strong></p>
    <p>The New Relic Python Agent now supports Python 3.7.</p>
  </li>
</ul>
<h2>Bug Fixes</h2>
<ul>
  <li>
    <p><strong>Agent raises a KeyError: 'NEW_RELIC_ADMIN_COMMAND' exception causing a crash</strong></p>
    <p>Under certain conditions, using the newrelic-admin wrapper script could cause an application to crash shortly after startup with a KeyError exception. The cause of the crash has been addressed.</p>
  </li>
  <li>
    <p><strong>Agent raises an AttributeError on Python 3 when using WSGI overrides with multiple app names</strong></p>
    <p>When using WSGI environ overrides to specify multiple app names as described in the docs <a href="https://docs.newrelic.com/docs/agents/manage-apm-agents/app-naming/use-multiple-names-app">https://docs.newrelic.com/docs/agents/manage-apm-agents/app-naming/use-m...</a> the agent will raise an AttributeError. This error has been corrected.</p>
  </li>
  <li>
    <p><strong>Agent raises an AttributeError exception under rare conditions when halting a trace</strong></p>
    <p>Under certain rare conditions, the agent might raise an exception when trying to trace an external call in a transaction that has been forcibly halted. The cause of the exception has been addressed.</p>
  </li>
  <li>
    <p><strong>Agent raises a RuntimeError exception under particular conditions when using the Tornado r3 instrumentation</strong></p>
    <p>When attempting to yield many times from a wrapped tornado.gen.coroutine when using Tornado's r3 instrumentation, a RuntimeError due to hitting the maximum recursion limit can occur. The cause of this exception has been patched.</p>
  </li>
</ul>
