
<h3>Notes</h3>
<p>This release of the Python agent is a bug fix release that addresses several recently reported issues.</p>
<p>The agent can be installed using easy_install/pip/distribute via the <a href="https://pypi.python.org/pypi/newrelic">Python Package Index</a> or can be downloaded directly from our <a href="http://download.newrelic.com/python_agent/release/">download site</a>.</p>
<h3>Bug Fixes</h3>
<ul>
  <li>
    <p><strong>WebSocket requests could cause application errors</strong></p>
    <p>When an application is using <a href="https://pypi.python.org/pypi/gevent-websocket/">gevent-websocket</a> to serve a mixture of WSGI and WebSocket endpoints, it is possible for WebSocket requests to interfere with the instrumentation of non-WebSocket requests, and cause application errors. While a <a href="https://bitbucket.org/noppo/gevent-websocket/commits/0df192940acd288e8a8f6d2dd30329a3381c90f1">fix</a> for this has been added to the 'gevent-websocket` main branch, that fix has not been released to PyPI yet. To address the problem now, the Python agent explicitly ignores WebSocket requests.</p>
  </li>
  <li>
    <p><strong>Disabling browser monitoring inadvertently disabled other features</strong></p>
    <p>Disabling browser monitoring had the unintended effect of disabling certain other Response-related features of the agent. Specifically, the <code>response.status</code> attribute was not recorded, and the <a href="https://docs.newrelic.com/docs/apm/transactions/cross-application-traces/cross-application-tracing">Cross Application Tracing</a> headers were not added to the HTTP headers of the outgoing response. With this release, those features now work when using the configuration setting of <code>browser.monitoring.enabled = False</code>.</p>
  </li>
  <li>
    <p><strong>Calling a Celery task within another task could cause a RuntimeError</strong></p>
    <p>The Python agent would throw a <code>RuntimeError('transaction already active')</code> when instrumenting a Celery task that performed the following combination of actions:</p>
    <ol>
      <li>Utilized the agent API to end the transaction early (<a href="https://docs.newrelic.com/docs/agents/python-agent/customization-extension/python-transaction-api#end_of_transaction"><code>end_of_transaction</code></a>), or to ignore the transaction altogether (<a href="https://docs.newrelic.com/docs/agents/python-agent/customization-extension/python-transaction-api#ignore_transaction"><code>ignore_transaction</code></a>).</li>
      <li>After ending or ignoring the transaction, called another Celery task that would run synchronously.</li>
    </ol>
    <p>This scenario, which most commonly occurs when taking advantage of <a href="http://docs.celeryproject.org/en/latest/userguide/canvas.html">Celery Workflows</a> to compose multiple tasks together, will no longer result in a <code>RuntimeError</code>.</p>
  </li>
</ul>
